### ISSUE TITLE
Restructure appliance logic

### ISSUE THREAD

**Issue by div3r** [NullTraining/project-team3#123]
In order for users to apply to workshops, users will be forced to register first, than they will be either able to apply to active workshop, and in other way to apply to show their interest in upcoming workshops.

**Comment by leovujanic** [comment]
This sounds to me like a big refactoring of the things I have done so far. If you go in this way, WorkshopApplicant entity won't be needed anymore, also invite functionality should be removed. We only need a new table that will hold information on which workshops user applied. We will also need to implement workshop apply to users that are already registered because we do not want one workshop per user (or we do?). In any case, it sounds like enough work for our homework. 😉 If you go with this I will wait for you to implement all these features and then we can create a list of all new features that will rely on that application logic.
